My_site/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using My_site.Domain.Attributes;
using My_site.Domain.Models;
using My_site.Services.Authentication;
using My_site.Services.Implementations;

namespace My_site.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class CatalogController : Controller
    {
        private readonly IComputerService _service;
        public CatalogController(IComputerService service)
        {
            _service = service;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetItems([FromBody] CatalogFilterViewModel filter)
        {
            var response = await _service.GetAll(filter);
            if (response == null) return BadRequest(response);
            return Ok(response);
        }
    }
}

My_site/Controllers/ComputersViewController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using My_site.DAL;

namespace My_site.Controllers
{
    [Authorize(Policy = "AdminPolicy")]
    public class ComputersViewController : Controller
    {
        private readonly ApplicationContext _context;

        public ComputersViewController(ApplicationContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            var computer = await _context.Computers.FindAsync(id);
            if (computer == null)
            {
                return NotFound();
            }
            return View(computer);
        }
        public IActionResult Create()
        {
            return View();
        }
    }
}

My_site/Controllers/LogsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using My_site.Services.Services;

namespace My_site.Controllers
{
    [Authorize(Policy = "UserPolicy")]
    public class LogsController : Controller
    {
        private readonly IUserActionLogger _userActionLogger;

        public LogsController(IUserActionLogger userActionLogger)
        {
            _userActionLogger = userActionLogger;
        }

        public async Task<IActionResult> Index()
        {
            var userActionCounts = await _userActionLogger.GetUserActionCounts();

            return View(userActionCounts);
        }
    }
}

My_site/Controllers/PrivacyController.cs
using Microsoft.AspNetCore.Mvc;
namespace My_site.Controllers
{
    public class PrivacyController : Controller
    {
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

My_site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My_site</title>
    <link rel="stylesheet" href="~/My_site.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body class="light">
    @{
        var IsAuthenticated = Context.Items["IsAuthenticated"] != null && (bool)Context.Items["IsAuthenticated"];
        var UserName = Context.Items["UserName"]?.ToString() ?? "Undefined";
        int? Role = Context.Items["Role"] as int?;
    }
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My_site</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Catalog" asp-action="Index">Catalog</a>
                        </li>
                        @if (Role == 1){
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="ComputersView" asp-action="Index">Edit</a>
                            </li>
                        }
                        @if (Role != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Logs" asp-action="Index">Statistics</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Privacy" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    @if (!IsAuthenticated){
                        <button class="btn me-2" id="authButton" onclick="openAuthModal()">Вход</button>
                        <button class="btn me-2" id="reg" onclick="openRegisterModal()">Регистрация</button>
                    }
                    else{
                        <a class="btn me-2" asp-area="" asp-controller="Profile" asp-action="Index">Профиль</a>
                        <a asp-controller="Profile" asp-action="Exit" class="btn btn-danger me-2">Выйти</a>
                    }
                    <button class="btn toggle-theme" id="button-theme">Тема</button>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div id="modalContainer"></div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - My_site - <a asp-area="" asp-controller="Privacy" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>